workflows:
  android-build:
    name: Android Build
    instance_type: linux
    max_build_duration: 120
    environment:
      node: 18.16.0
      java: 11
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Run EAS build
        script: |
          npm install -g eas-cli
          eas build --platform android --non-interactive --wait
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
    publishing:
      email:
        recipients:
          - $CODEMAGIC_EMAIL
